#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM

trap_function() {
    echo "I am invincible!!!"
}
trap trap_function SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
